### ISSUE TITLE
node ids 

### ISSUE THREAD

**Issue by iwargogaming** [geode-sdk/NodeIDs#58] opened 2024-05-16 21:31 UTC
it crashes my game

**Comment by hiimjustin000** [comment] 2024-05-16 21:32
what os

**Comment by iwargogaming** [comment] 2024-05-16 21:36
mac os

**Comment by RoootTheFox** [comment] 2024-05-16 21:58
crashlog?

**Comment by hiimjustin000** [comment] 2024-05-16 22:02
Appears to be caused by `diamond-icon` in LevelCell. I still do not know the root cause.

**Comment by hiimjustin000** [comment] 2024-05-17 19:09
Fixed in v1.10.2

**Closed** 2024-06-04 22:12 UTC
